# This example displays a form before starting the notebooks server to
# enter an Ocean Spark API key.
# All notebook servers launched by JupyterHub will use Ocean Spark.
#
# The Ocean Spark URL is controlled by configuration
# `c.OceanSparkSingleUserKubeSpawner.gateway_url`. Please set it to
# your own Ocean Spark URL.
proxy:
    # Generate a custom secret for your installation with:
    #
    #   openssl rand -hex 32
    #
    secretToken: ea1a28fc09fff627f32dea783d658707cf8d35f8b98fdd4a98c5a0c8d5ba4920
hub:
  extraConfig:
        oceanspark.py: |
            from kubespawner import KubeSpawner
            from traitlets import Unicode

            class DataMechanicsSingleUserKubeSpawner(KubeSpawner):
                """A KubeSpawner subclass that launches notebook kernels on the
                Ocean Spark platform rather than on a Jupyter server pod.
                """

                oceanspark_url = Unicode(
                None,
                allow_none=True,
                config=True,
                help="""
                The URL to your Data Mechanics platform notebook API.
                Typically: https://api.spotinst.io/ocean/spark/cluster/<cluster-id>/notebook
                """,
            )

                async def options_from_form(self, form_data):
                    options = super().options_from_form(form_data)
                    options["oceanspark_api_key"] = form_data[f"api_key"][0]
                    return options

                async def load_user_options(self):
                    await super().load_user_options()
                    datamechanics_api_key = self.user_options["oceanspark_api_key"]
                    self.args = [
                        f"--gateway-url={self.oceanspark_url}",
                        f"--GatewayClient.auth_token={datamechanics_api_key}",
                        "--GatewayClient.request_timeout=600",
                    ]
                    self.log.info("Using Data Mechanics. Args: " + " ".join(self.args))

            c.JupyterHub.spawner_class = DataMechanicsSingleUserKubeSpawner
            c.DataMechanicsSingleUserKubeSpawner.datamechanics_url = "https://api.spotinst.io/ocean/spark/cluster/<cluster-id>/notebooks/"
            c.DataMechanicsSingleUserKubeSpawner.options_form = """
                Please enter an Ocean Spark API key: <input name="api_key" />
            """
